---
stages:
  - test
  - build
  - post-test

include:
  - component: $CI_SERVER_FQDN/ci/security/bundle@1
  - component: $CI_SERVER_FQDN/ci/golang/init-vet@2
  - component: $CI_SERVER_FQDN/ci/golang/lint@2
  - component: $CI_SERVER_FQDN/ci/golang/test@2
  - component: $CI_SERVER_FQDN/ci/docker/build-and-scan@4
    inputs:
      name: server
      image: server
      tags: latest,$CI_COMMIT_REF_NAME
      architectures: linux/amd64,linux/arm64
      rules_changes:
        - .dockerignore
        - Dockerfile
        - go.mod
        - go.sum
        - "**/*.go"
        - $CI_CONFIG_PATH
  - component: $CI_SERVER_FQDN/ci/golang/build-binaries@2
    inputs:
      binary_name: gltgr
      build_architectures: linux/amd64,linux/arm64,darwin/arm64
